import type { AssessmentInput } from "./types";

export type PersonaPreset = {
  id: "priya" | "ravi" | "anita";
  summary: string;
  facts: Partial<AssessmentInput>;
  knownFacts: string[];
  assumptionLabels: string[];
  walkthrough: AssessmentInput;
};

export const PERSONAS: PersonaPreset[] = [
  {
    id: "priya",
    summary: "Stable salary · wedding · existing car EMI",
    facts: {
      name: "Priya",
      city: "Bengaluru",
      purpose: "Wedding",
      purposeUses: ["personal-expense"],
      requestedAmount: 800_000,
      consideredProduct: "personal",
      age: 29,
      incomeType: "salaried",
      monthlyIncome: { min: 110_000, max: 110_000 },
      currentDebtPayments: 14_000,
      debtZeroConfirmed: false,
      creditStatus: { kind: "exact", score: 780 },
      employmentStatus: "permanent",
      employmentMonths: 60,
      activeDebts: [{ label: "Car loan", type: "vehicle-loan", balance: 336_000, emi: 14_000, monthsLeft: 24 }],
    },
    knownFacts: ["₹1,10,000 net salary", "₹14,000 car EMI", "780 score", "₹28,000 rent", "₹8L request"],
    assumptionLabels: ["Other essentials ₹17,000/month", "No recent payment issue", "Six months of emergency savings"],
    walkthrough: {
      name: "Priya",
      city: "Bengaluru",
      purpose: "Wedding",
      purposeUses: ["personal-expense"],
      requestedAmount: 800_000,
      consideredProduct: "personal",
      age: 29,
      incomeType: "salaried",
      monthlyIncome: { min: 110_000, max: 110_000 },
      currentDebtPayments: 14_000,
      debtZeroConfirmed: false,
      essentialExpenses: 45_000,
      creditStatus: { kind: "exact", score: 780 },
      recentPaymentIssue: false,
      employmentStatus: "permanent",
      employmentMonths: 60,
      variableIncomeShare: 0,
      otherHouseholdIncome: 0,
      dependants: 0,
      emergencySavingsMonths: 6,
      activeDebts: [{ label: "Car loan", type: "vehicle-loan", balance: 336_000, emi: 14_000, monthsLeft: 24 }],
    },
  },
  {
    id: "ravi",
    summary: "Established kirana · stock + delivery vehicle",
    facts: {
      name: "Ravi",
      city: "Mysuru",
      purpose: "Second stock line and a delivery vehicle",
      purposeUses: ["working-capital", "vehicle"],
      requestedAmount: 1_500_000,
      consideredProduct: "business",
      age: 42,
      incomeType: "self-employed",
      monthlyIncome: { min: 40_000, max: 80_000 },
      currentDebtPayments: 0,
      debtZeroConfirmed: true,
      creditStatus: { kind: "no-history" },
      businessVintageMonths: 168,
      itrAnnualIncome: 420_000,
      otherHouseholdIncome: 18_000,
      collateral: {
        type: "property",
        value: 4_500_000,
        ownedByApplicant: true,
        encumbered: false,
        essentialAsset: true,
        willingToPledge: true,
      },
    },
    knownFacts: ["₹40k–₹80k cash income", "₹4.2L ITR", "₹45L unencumbered shop", "No credit history", "₹15L request"],
    assumptionLabels: ["₹25,000 essentials", "₹5L vehicle + ₹10L stock split", "New ₹6L LCV with ₹1L down payment", "Two months of emergency savings", "No recent payment issue"],
    walkthrough: {
      name: "Ravi",
      city: "Mysuru",
      purpose: "Second stock line and a delivery vehicle",
      purposeUses: ["working-capital", "vehicle"],
      requestedAmount: 1_500_000,
      consideredProduct: "business",
      age: 42,
      incomeType: "self-employed",
      monthlyIncome: { min: 40_000, max: 80_000 },
      currentDebtPayments: 0,
      debtZeroConfirmed: true,
      essentialExpenses: 25_000,
      creditStatus: { kind: "no-history" },
      recentPaymentIssue: false,
      businessVintageMonths: 168,
      monthlyTurnover: { min: 150_000, max: 250_000 },
      monthlyNetProfit: { min: 40_000, max: 80_000 },
      itrAnnualIncome: 420_000,
      otherHouseholdIncome: 18_000,
      dependants: 1,
      emergencySavingsMonths: 2,
      collateral: {
        type: "property",
        value: 4_500_000,
        ownedByApplicant: true,
        encumbered: false,
        essentialAsset: true,
        willingToPledge: true,
      },
      vehicle: {
        class: "three-wheeler-lcv",
        use: "business",
        condition: "new",
        price: 600_000,
        downPayment: 100_000,
      },
      businessSplit: { workingCapital: 1_000_000, equipment: 0, vehicle: 500_000 },
      expectedNetIncomeUplift: 15_000,
      upliftEvidence: "weak",
    },
  },
  {
    id: "anita",
    summary: "Gig + tailoring · app loans · bounced EMI",
    facts: {
      name: "Anita",
      city: "Hubballi",
      purpose: "Electric scooter to increase delivery runs",
      purposeUses: ["vehicle"],
      requestedAmount: 150_000,
      consideredProduct: "two-wheeler",
      age: 35,
      incomeType: "informal",
      monthlyIncome: { min: 26_000, max: 30_000 },
      creditStatus: { kind: "unknown" },
      recentPaymentIssue: true,
      dependants: 3,
    },
    knownFacts: ["₹26k–₹30k informal income", "Three app loans", "₹35,000 outstanding", "One bounced EMI", "₹1.5L request"],
    assumptionLabels: ["₹6,000 current monthly repayments", "₹22,000 essential expenses", "No emergency savings", "Bounce remains unresolved"],
    walkthrough: {
      name: "Anita",
      city: "Hubballi",
      purpose: "Electric scooter to increase delivery runs",
      purposeUses: ["vehicle"],
      requestedAmount: 150_000,
      consideredProduct: "two-wheeler",
      age: 35,
      incomeType: "informal",
      monthlyIncome: { min: 26_000, max: 30_000 },
      currentDebtPayments: 6_000,
      debtZeroConfirmed: false,
      essentialExpenses: 22_000,
      creditStatus: { kind: "unknown" },
      recentPaymentIssue: true,
      lowestRecentIncome: 26_000,
      informalActiveMonths: 12,
      informalPaidDaysPerMonth: 24,
      dependants: 3,
      emergencySavingsMonths: 0,
      activeDebts: [
        { label: "App loan 1", type: "app-loan", balance: 15_000, emi: 2_500, annualRate: 32, highCost: true },
        { label: "App loan 2", type: "app-loan", balance: 12_000, emi: 2_000, annualRate: 34, highCost: true },
        { label: "App loan 3", type: "app-loan", balance: 8_000, emi: 1_500, annualRate: 30, highCost: true },
      ],
      delinquency: { monthsAgo: 1, unresolvedAmount: 2_500, resolved: false },
      vehicle: {
        class: "two-wheeler",
        use: "income-generating",
        condition: "new",
        price: 170_000,
        downPayment: 20_000,
      },
      expectedNetIncomeUplift: 8_000,
      upliftEvidence: "weak",
    },
  },
];

export const WALKTHROUGH_INPUTS = Object.fromEntries(PERSONAS.map((persona) => [persona.id, persona.walkthrough]));
